"""
============================================================
Data Models for Knitting Tracker Application
============================================================
This module defines the data structures (models) used throughout
the knitting tracker application. Each class represents a table
in the database.

Author: Anna Khoriakova
Last Updated: 2026-08-21
============================================================
"""

from dataclasses import dataclass
from typing import Optional
from datetime import date

@dataclass
class Pattern:
    """
    Represents a knitting pattern in the system.
    
    A pattern is a set of instructions for creating a knitted item.
    Patterns can be designed by various designers and are referenced
    by projects that use them.
    
    Attributes:
        pattern_id: Unique identifier (auto-generated by database)
        pattern_name: Name of the pattern (e.g., "Aran Sweater", "Lace Shawl")
        designer: Name of the pattern designer (optional, can be None)
    """
    pattern_id: Optional[int] = None  # None indicates a new unsaved pattern
    pattern_name: str = ""            # Must be provided for new patterns
    designer: Optional[str] = None    # Can be left empty if designer is unknown
