"""
============================================================
Data Models for Knitting Tracker Application
============================================================
This module defines the data structures (models) used throughout
the knitting tracker application. Each class represents a table
in the database.

Author: Anna Khoriakova
Last Updated: 2026-08-21
============================================================
"""

from dataclasses import dataclass
from typing import Optional
from datetime import date

@dataclass
class Pattern:
    """
    Represents a knitting pattern in the system.
    
    A pattern is a set of instructions for creating a knitted item.
    Patterns can be designed by various designers and are referenced
    by projects that use them.
    
    Attributes:
        pattern_id: Unique identifier (auto-generated by database)
        pattern_name: Name of the pattern (e.g., "Aran Sweater", "Lace Shawl")
        designer: Name of the pattern designer (optional, can be None)
    """
    pattern_id: Optional[int] = None  # None indicates a new unsaved pattern
    pattern_name: str = ""            # Must be provided for new patterns
    designer: Optional[str] = None    # Can be left empty if designer is unknown

@dataclass
class Needle:
    """
    Represents a knitting needle in the system.
    
    Needles come in various sizes, types, and materials. Each project
    requires at least one primary needle, though some projects may use
    multiple needle sizes.
    
    Attributes:
        needle_id: Unique identifier (auto-generated by database)
        needle_size_mm: Size in millimeters (e.g., 4.0, 5.5, 8.0)
        needle_type: Type of needle (Circular, Straight, DPN, Interchangeable)
        needle_material: Material the needle is made from (Wood, Metal, Bamboo, Plastic)
        needle_length: Length in inches as string (e.g., "24", "32", "40")
        needle_brand: Brand manufacturer (e.g., "KnitPro", "Addi", "ChiaoGoo")
    """
    needle_id: Optional[int] = None
    needle_size_mm: float = 0.0            # Must be > 0 for valid needles
    needle_type: str = ""                  # Required: Circular, Straight, DPN, Interchangeable
    needle_material: Optional[str] = None  # e.g., Wood, Metal, Bamboo, Plastic
    needle_length: Optional[str] = None    # e.g., "24", "32", "40"
    needle_brand: Optional[str] = None     # e.g., "KnitPro", "Addi"
    