"""
============================================================
Data Models for Knitting Tracker Application
============================================================
This module defines the data structures (models) used throughout
the knitting tracker application. Each class represents a table
in the database.

Author: Anna Khoriakova
Last Updated: 2026-08-22
============================================================
"""

from dataclasses import dataclass
from typing import Optional
from datetime import date

@dataclass
class Pattern:
    """
    Represents a knitting pattern in the system.
    
    A pattern is a set of instructions for creating a knitted item.
    Patterns can be designed by various designers and are referenced
    by projects that use them.
    
    Attributes:
        pattern_id: Unique identifier (auto-generated by database)
        pattern_name: Name of the pattern (e.g., "Aran Sweater", "Lace Shawl")
        designer: Name of the pattern designer (optional, can be None)
    """
    pattern_id: Optional[int] = None  # None indicates a new unsaved pattern
    pattern_name: str = ""            # Must be provided for new patterns
    designer: Optional[str] = None    # Can be left empty if designer is unknown

@dataclass
class Needle:
    """
    Represents a knitting needle in the system.
    
    Needles come in various sizes, types, and materials. Each project
    requires at least one primary needle, though some projects may use
    multiple needle sizes.
    
    Attributes:
        needle_id: Unique identifier (auto-generated by database)
        needle_size_mm: Size in millimeters (e.g., 4.0, 5.5, 8.0)
        needle_type: Type of needle (Circular, Straight, DPN, Interchangeable)
        needle_material: Material the needle is made from (Wood, Metal, Bamboo, Plastic)
        needle_length: Length in inches as string (e.g., "24", "32", "40")
        needle_brand: Brand manufacturer (e.g., "KnitPro", "Addi", "ChiaoGoo")
    """
    needle_id: Optional[int] = None
    needle_size_mm: float = 0.0            # Must be > 0 for valid needles
    needle_type: str = ""                  # Required: Circular, Straight, DPN, Interchangeable
    needle_material: Optional[str] = None  # e.g., Wood, Metal, Bamboo, Plastic
    needle_length: Optional[str] = None    # e.g., "24", "32", "40"
    needle_brand: Optional[str] = None     # e.g., "KnitPro", "Addi"

@dataclass
class Yarn:
    """
    Represents a type/colour of yarn in the system.
    
    Yarn is characterized by brand, line, colour, and weight. Each yarn
    can be used in multiple projects, and each project can use multiple
    yarns (e.g., for stripes or colourwork).
    
    Attributes:
        yarn_id: Unique identifier (auto-generated by database)
        yarn_brand: Brand name (e.g., "Malabrigo", "Cascade", "Rowan")
        yarn_line: Line/product name within the brand (e.g., "Rios", "Heritage")
        colour_name: Colourway name (e.g., "Whale's Road", "Ruby Red")
        dye_lot: Dye lot number for matching colours between skeins
        weight_category: Yarn weight category (DK, Worsted, Fingering, etc.)
        total_yardage: Yards per skein (important for calculating how many skeins needed)
    """
    yarn_id: Optional[int] = None
    yarn_brand: str = ""                    # Required: Brand name
    yarn_line: Optional[str] = None         # e.g., "Rios", "Heritage", "Wool-Ease"
    colour_name: Optional[str] = None       # e.g., "Whale's Road", "Ruby Red"
    dye_lot: Optional[str] = None           # Important for matching skeins
    weight_category: Optional[str] = None   # e.g., "DK", "Worsted", "Fingering"
    total_yardage: Optional[int] = None     # Yards per skein

@dataclass
class Project:
    """
    Represents a complete knitting project in the system.
    
    A project is the main entity in the tracker, combining a pattern,
    needles, and yarns into a knitting project. Projects track
    progress from planning through completion.
    
    This entity references other entities:
    - pattern_id: Links to the pattern being used
    - needle_id: Links to the primary needle being used
    - yarns: List of yarn objects associated with this project (via PROJECT_YARN table)
    
    Attributes:
        project_id: Unique identifier (auto-generated by database)
        project_name: Name of the project (e.g., "My Aran Sweater")
        start_date: Date project was started (ISO format: YYYY-MM-DD)
        end_date: Date project was completed (NULL if still in progress)
        status: Current status of the project
            Allowed values: 'Planning', 'WIP', 'Blocking', 'Finished', 'Frogged', 'Abandoned'
        recipient: Who the project is for ("Me", "Gift", person's name, etc.)
        pattern_id: Foreign key referencing PATTERN table
        needle_id: Foreign key referencing NEEDLE table
        yarns: List of Yarn objects used in this project (populated when retrieving from DB)
    
    Example:
        project = Project(
            project_name="My First Sweater",
            start_date="2026-08-21",
            status="WIP",
            recipient="Me",
            pattern_id=1,
            needle_id=3
        )
    """
    project_id: Optional[int] = None
    project_name: str = ""            # Required: Name of the project
    start_date: Optional[str] = None  # ISO format: YYYY-MM-DD
    end_date: Optional[str] = None    # None means project is still in progress
    status: str = "Planning"          # Default status for new projects
    recipient: Optional[str] = None   # e.g., "Me", "Gift", or person's name
    pattern_id: int = 0               # Foreign key to PATTERN table (required)
    needle_id: int = 0                # Foreign key to NEEDLE table (required)
    yarns: list = None                # List of Yarn objects (populated by database layer)

    def __post_init__(self):
        """
        Post-initialization hook that runs after the dataclass __init__.
        
        This ensures that yarns is always a list, even if it wasn't provided
        during initialization. This prevents NoneType errors when iterating
        over yarns in the application code.
        
        The database layer will populate this list when retrieving projects
        that have associated yarns via the PROJECT_YARN junction table.
        """
        if self.yarns is None:
            self.yarns = []
